worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    # Määritellään upstream-pooli kolmelle backend-palvelimelle
    upstream backend_tcp {
        server 172.20.0.5:8082;   # Palvelin 1
        server 172.20.0.3:8082;   # Palvelin 2
        server 172.20.0.4:8082;   # Palvelin 3
        # Voit lisätä esim. "max_fails" ja "fail_timeout" jos haluat tarkempaa hallintaa
    }

    # TCP-palvelin, joka kuuntelee porttia ja välittää liikenteen upstreamiin
    server {
        listen 8084;            # Portti, johon Nginx ottaa vastaan yhteydet
        proxy_pass backend_tcp; # Välitetään yhteydet upstream-pooliin
    }
}
